package utils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Stream;

/**
 * Created by antoine on 10/10/15.
 */
public class TetraBuffer {

    private static TetraBuffer tb = null;
    private ArrayList<String> lOne = null;
    private ArrayList<String> reduceLone = null;

    public TetraBuffer() {}

    public static TetraBuffer getInstance() {
        if(tb == null){
            tb = new TetraBuffer();
        }
        return tb;
    }

    public ArrayList<String> getReduceLOne(){
        if(this.reduceLone == null){
            this.reduceLone = new ArrayList<>(126);

            reduceLone.add("GTTG");
            reduceLone.add("TGCT");
            reduceLone.add("TGTC");
            reduceLone.add("TGTA");
            reduceLone.add("ACTG");
            reduceLone.add("GTTT");
            reduceLone.add("ACCT");
            reduceLone.add("ACTC");
            reduceLone.add("ACTA");
            reduceLone.add("TGTT");
            reduceLone.add("ACCG");
            reduceLone.add("GCCA");
            reduceLone.add("ACCC");
            reduceLone.add("GCCC");
            reduceLone.add("ACCA");
            reduceLone.add("TAGA");
            reduceLone.add("CGGA");
            reduceLone.add("GCAG");
            reduceLone.add("GTCA");
            reduceLone.add("TAGG");
            reduceLone.add("GTCC");
            reduceLone.add("GTCG");
            reduceLone.add("TGCG");
            reduceLone.add("TGCC");
            reduceLone.add("TGCA");
            reduceLone.add("GTTA");
            reduceLone.add("ACTT");
            reduceLone.add("TAGT");
            reduceLone.add("GTTC");
            reduceLone.add("GTCT");
            reduceLone.add("CTAG");
            reduceLone.add("CTAC");
            reduceLone.add("AAAT");
            reduceLone.add("ATGG");
            reduceLone.add("CTAA");
            reduceLone.add("ATGA");
            reduceLone.add("AAAG");
            reduceLone.add("GAAA");
            reduceLone.add("AAAC");
            reduceLone.add("GAAC");
            reduceLone.add("AACA");
            reduceLone.add("GCTC");
            reduceLone.add("GCTG");
            reduceLone.add("CTAT");
            reduceLone.add("GCTT");
            reduceLone.add("ATGT");
            reduceLone.add("TTAG");
            reduceLone.add("CTTA");
            reduceLone.add("TTAC");
            reduceLone.add("TTAA");
            reduceLone.add("CTCG");
            reduceLone.add("CCAT");
            reduceLone.add("CTCC");
            reduceLone.add("AACT");
            reduceLone.add("CTCA");
            reduceLone.add("AATA");
            reduceLone.add("GCGA");
            reduceLone.add("GACA");
            reduceLone.add("CCAG");
            reduceLone.add("AACG");
            reduceLone.add("GACC");
            reduceLone.add("GCGG");
            reduceLone.add("CCAC");
            reduceLone.add("AACC");
            reduceLone.add("GACG");
            reduceLone.add("CCAA");
            reduceLone.add("GAAG");
            reduceLone.add("CCCA");
            reduceLone.add("GTGA");
            reduceLone.add("GTGC");
            reduceLone.add("GTGG");
            reduceLone.add("TTCG");
            reduceLone.add("TCAT");
            reduceLone.add("AGAT");
            reduceLone.add("TTCC");
            reduceLone.add("CCTG");
            reduceLone.add("CCCT");
            reduceLone.add("CCTC");
            reduceLone.add("CCTA");
            reduceLone.add("TTCT");
            reduceLone.add("AGAC");
            reduceLone.add("AGAA");
            reduceLone.add("CCCG");
            reduceLone.add("GCGT");
            reduceLone.add("TCAA");
            reduceLone.add("GACT");
            reduceLone.add("TCAG");
            reduceLone.add("TCAC");
            reduceLone.add("TTCA");
            reduceLone.add("CCTT");
            reduceLone.add("TCCT");
            reduceLone.add("AGCT");
            reduceLone.add("AGCG");
            reduceLone.add("AGCC");
            reduceLone.add("AGCA");
            reduceLone.add("GGCA");
            reduceLone.add("CCGC");
            reduceLone.add("CCGA");
            reduceLone.add("TCCC");
            reduceLone.add("TCCA");
            reduceLone.add("TCCG");
            reduceLone.add("CATT");
            reduceLone.add("CATG");
            reduceLone.add("CATC");
            reduceLone.add("CATA");
            reduceLone.add("CCGG");
            reduceLone.add("TAAC");
            reduceLone.add("TAAA");
            reduceLone.add("TAAG");
            reduceLone.add("ATAG");
            reduceLone.add("TATG");
            reduceLone.add("TATT");
            reduceLone.add("CGTG");
            reduceLone.add("GCAA");


            reduceLone.addAll(this.getS12());
        }
        return this.reduceLone;
    }

    public ArrayList<String>  getLOne(){

        if(this.lOne == null){
            this.lOne = new ArrayList<String>(228);

            lOne.add("GTTG");
            lOne.add("TGCT");
            lOne.add("TGTC");
            lOne.add("TGTA");
            lOne.add("ACTG");
            lOne.add("GTTT");
            lOne.add("ACCT");
            lOne.add("ACTC");
            lOne.add("ACTA");
            lOne.add("TGTT");
            lOne.add("ACCG");
            lOne.add("GCCA");
            lOne.add("ACCC");
            lOne.add("GCCC");
            lOne.add("ACCA");
            lOne.add("TAGA");
            lOne.add("CGGA");
            lOne.add("GCAG");
            lOne.add("GTCA");
            lOne.add("TAGG");
            lOne.add("GTCC");
            lOne.add("GTCG");
            lOne.add("TGCG");
            lOne.add("TGCC");
            lOne.add("TGCA");
            lOne.add("GTTA");
            lOne.add("ACTT");
            lOne.add("TAGT");
            lOne.add("GTTC");
            lOne.add("GTCT");
            lOne.add("CTAG");
            lOne.add("CTAC");
            lOne.add("AAAT");
            lOne.add("ATGG");
            lOne.add("CGGT");
            lOne.add("CTAA");
            lOne.add("ATGA");
            lOne.add("AAAG");
            lOne.add("GAAA");
            lOne.add("CGGG");
            lOne.add("AAAC");
            lOne.add("GAAC");
            lOne.add("AACA");
            lOne.add("ACGC");
            lOne.add("ACGA");
            lOne.add("GCTC");
            lOne.add("GCCT");
            lOne.add("GCTG");
            lOne.add("CTAT");
            lOne.add("GCTT");
            lOne.add("ATGT");
            lOne.add("TTAG");
            lOne.add("CTTA");
            lOne.add("TTAC");
            lOne.add("TTAA");
            lOne.add("TGGT");
            lOne.add("CTCG");
            lOne.add("CCAT");
            lOne.add("AATG");
            lOne.add("CTCC");
            lOne.add("AACT");
            lOne.add("CTCA");
            lOne.add("AATC");
            lOne.add("ACGT");
            lOne.add("AATA");
            lOne.add("TTAT");
            lOne.add("GCGA");
            lOne.add("GACA");
            lOne.add("CCAG");
            lOne.add("AACG");
            lOne.add("GACC");
            lOne.add("ACGG");
            lOne.add("GCGG");
            lOne.add("CCAC");
            lOne.add("AACC");
            lOne.add("GACG");
            lOne.add("CCAA");
            lOne.add("GAAG");
            lOne.add("CCCA");
            lOne.add("GTGA");
            lOne.add("GTGC");
            lOne.add("TGGC");
            lOne.add("TGGA");
            lOne.add("GAAT");
            lOne.add("GTGG");
            lOne.add("CTTT");
            lOne.add("TGGG");
            lOne.add("CTTG");
            lOne.add("AATT");
            lOne.add("CTTC");
            lOne.add("TTCG");
            lOne.add("TCAT");
            lOne.add("AGAT");
            lOne.add("TTCC");
            lOne.add("TTTC");
            lOne.add("TTTA");
            lOne.add("CCTG");
            lOne.add("CCCT");
            lOne.add("CCTC");
            lOne.add("CCTA");
            lOne.add("TTTG");
            lOne.add("TTCT");
            lOne.add("AGAC");
            lOne.add("AGAA");
            lOne.add("CCCG");
            lOne.add("CAAA");
            lOne.add("AAGC");
            lOne.add("AAGA");
            lOne.add("GATA");
            lOne.add("GATC");
            lOne.add("GCGT");
            lOne.add("TCAA");
            lOne.add("GACT");
            lOne.add("GATG");
            lOne.add("TCAG");
            lOne.add("TCAC");
            lOne.add("TTCA");
            lOne.add("GATT");
            lOne.add("CCTT");
            lOne.add("CTGT");
            lOne.add("TCTG");
            lOne.add("TCCT");
            lOne.add("AGTG");
            lOne.add("TCTT");
            lOne.add("AGCT");
            lOne.add("AGTC");
            lOne.add("AGTA");
            lOne.add("CAAT");
            lOne.add("CTGG");
            lOne.add("CTGC");
            lOne.add("AAGT");
            lOne.add("AGCG");
            lOne.add("CTGA");
            lOne.add("GAGC");
            lOne.add("AGCC");
            lOne.add("AGCA");
            lOne.add("GAGG");
            lOne.add("CAAG");
            lOne.add("AAGG");
            lOne.add("GGCA");
            lOne.add("CAAC");
            lOne.add("GGAA");
            lOne.add("CACC");
            lOne.add("GGAC");
            lOne.add("CCGC");
            lOne.add("CCGA");
            lOne.add("GGAG");
            lOne.add("TCCC");
            lOne.add("TCCA");
            lOne.add("GGAT");
            lOne.add("TCCG");
            lOne.add("AGTT");
            lOne.add("TCTA");
            lOne.add("GGTT");
            lOne.add("CATT");
            lOne.add("TTGG");
            lOne.add("TTGT");
            lOne.add("CATG");
            lOne.add("CACT");
            lOne.add("CCGT");
            lOne.add("CATC");
            lOne.add("CATA");
            lOne.add("CACG");
            lOne.add("CCGG");
            lOne.add("GGCC");
            lOne.add("GGCG");
            lOne.add("GAGT");
            lOne.add("TAAC");
            lOne.add("TAAA");
            lOne.add("GGTA");
            lOne.add("GGTC");
            lOne.add("GGCT");
            lOne.add("GGTG");
            lOne.add("TAAG");
            lOne.add("TTGC");
            lOne.add("TTGA");
            lOne.add("ATAG");
            lOne.add("TATG");
            lOne.add("TATT");
            lOne.add("ATAC");
            lOne.add("AGGT");
            lOne.add("ATAA");
            lOne.add("CGAG");
            lOne.add("AGGG");
            lOne.add("CGAC");
            lOne.add("GGGA");
            lOne.add("CGAA");
            lOne.add("AGGC");
            lOne.add("GGGC");
            lOne.add("AGGA");
            lOne.add("CAGG");
            lOne.add("CAGC");
            lOne.add("CAGA");
            lOne.add("TCGG");
            lOne.add("TACC");
            lOne.add("TCGC");
            lOne.add("TACA");
            lOne.add("TCGA");
            lOne.add("TACT");
            lOne.add("TCGT");
            lOne.add("TATC");
            lOne.add("GTAT");
            lOne.add("TGAT");
            lOne.add("CGTG");
            lOne.add("CGCT");
            lOne.add("ACAT");
            lOne.add("CGTC");
            lOne.add("ATCC");
            lOne.add("ATCA");
            lOne.add("CAGT");
            lOne.add("ACAG");
            lOne.add("CGCC");
            lOne.add("ACAA");
            lOne.add("GCAA");
            lOne.add("CGCA");
            lOne.add("GCAC");
            lOne.add("GGGT");
            lOne.add("GTAA");
            lOne.add("ATTT");
            lOne.add("GTAC");
            lOne.add("GTAG");
            lOne.add("TGAC");
            lOne.add("TGAA");
            lOne.add("ATTG");
            lOne.add("ATCT");
            lOne.add("CGTT");
            lOne.add("ATTC");
            lOne.add("TGAG");
        }
//        System.out.println("lOne size : " + this.lOne.size());
        return this.lOne;
//        return this.getReduceLOne();

    }

    public ArrayList<String> getS12(){
        ArrayList<String> s12 = new ArrayList<String>(12);


        s12.add("TGCA");
        s12.add("CTAG");
        s12.add("TTAA");
        s12.add("ACGT");
        s12.add("AATT");
        s12.add("GATC");
        s12.add("AGCT");
        s12.add("CATG");
        s12.add("CCGG");
        s12.add("GGCC");
        s12.add("TCGA");
        s12.add("GTAC");
        
        return s12;
    }

}
